name: Build & Test
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os : ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Pack
        run: |
          dotnet pack UltralightNet.Binaries
          dotnet pack UltralightNet
          dotnet pack UltralightNet.AppCore
          dotnet pack UltralightNet.Resources
      - run: | # missing libraries workaround
          sudo add-apt-repository ppa:linuxuprising/libpng12
          sudo apt update
          sudo apt install libpng12-0
          find /usr/lib -name "libffi.so*"
          sudo ln -s  /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0  /usr/lib/x86_64-linux-gnu/libffi.so.6
        if: matrix.os=='ubuntu-latest'
      - name: Test Application
        run: dotnet run --project UltralightNet.TestApplication
      - name: Test
        run: dotnet test UltralightNet.Test/UltralightNet.Test.csproj --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.UseSourceLink=true
      - run: |
          curl -s https://codecov.io/bash > codecov
          chmod +x codecov
          ./codecov -f "UltralightNet.Test/TestResults/*/coverage.opencover.xml"
